import '../scss/app.scss';
import '../img/logo.png';
import '../img/add.png';
import '../img/delete.png';
import '../img/edit.png';
import '../img/back3.gif'
import '../img/back4.jpg'
import '../img/modalback.jpg'
import '../img/social-1_logo-evernote.svg';
import '../img/social-1_logo-facebook.svg';
import '../img/social-1_logo-google-plus.svg';
import '../img/social-1_logo-instagram.svg';
import 'bootstrap';
import 'jquery';
import 'jquery-ui';
import './nav/view';
import './nav/controller';
import './board/view';
import './board/controller';
import './list/view';
import './list/controller';
import './service';
